import os
from pathlib import Path

# --- Paths ---
BASE_DIR = Path(__file__).parent.absolute()
ASSETS_DIR = BASE_DIR / "assets"
ICONS_DIR = ASSETS_DIR / "icons"
THEMES_DIR = ASSETS_DIR / "themes"
SOUNDS_DIR = ASSETS_DIR / "sounds"

# --- Camera Settings ---
CAMERA_INDEX = 0  # Default webcam
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30
MIRROR_FEED = True

# --- Hand Tracking ---
HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.7 
MAX_NUM_HANDS = 2
MP_MODEL_COMPLEXITY = 2
MP_MIN_DETECTION_CONFIDENCE = 0.8
MP_MIN_TRACKING_CONFIDENCE = 0.8
LANDMARK_SMOOTHING_FACTOR = 0.55
LANDMARK_SMOOTHING_ALPHA = 1.0 - LANDMARK_SMOOTHING_FACTOR
ADAPTIVE_LANDMARK_SMOOTHING = True
LANDMARK_SMOOTHING_MIN_FACTOR = 0.45
LANDMARK_SMOOTHING_MAX_FACTOR = 0.90
LANDMARK_SMOOTHING_VELOCITY_REF = 28.0  # pixels/frame

# --- Gesture Settings ---
PINCH_THRESHOLD = 0.28  # Distance between thumb and index tip
PINCH_RATIO_THRESHOLD = 0.35
EXPAND_THRESHOLD = 0.15 # Distance for Expand gesture
GESTURE_COOLDOWN = 0.3  # Seconds
HOLD_TIME_FOR_EXPAND = 0.6 # Seconds to hold expand to open
EXPAND_CONFIRMATION_FRAMES = 6
OPEN_PALM_CONFIRMATION_FRAMES = 5
FINGER_EXTENDED_RATIO = 1.15
FINGER_FOLDED_RATIO = 0.95
FINGER_EXTENDED_ANGLE = 160
FINGER_BENT_ANGLE = 60
FINGER_EXTENDED_ANGLE_DEG = FINGER_EXTENDED_ANGLE
FINGER_BENT_ANGLE_DEG = FINGER_BENT_ANGLE
FINGER_SPREAD_EXTENDED_ANGLE_DEG = 145
FINGER_SPREAD_BENT_ANGLE_DEG = 75
SWIPE_MIN_DISTANCE_PX = 110
SWIPE_MAX_DURATION_S = 0.45
SWIPE_TWO_MIN_DISTANCE_PX = 90
SWIPE_TWO_MAX_DURATION_S = 0.45
DOUBLE_TAP_WINDOW_S = 0.4
DOUBLE_TAP_MOTION_PX = 16
DOUBLE_TAP_TAP_TIMEOUT_S = 0.24
DOUBLE_TAP_STABLE_FRAMES = 2
DOUBLE_TAP_MIN_CONFIDENCE = 0.5
MODE_TOGGLE_HOLD_S = 5.0
GESTURE_STABLE_FRAMES = 6
GESTURE_MIN_STABLE_FRAMES = GESTURE_STABLE_FRAMES
GESTURE_MIN_CONFIDENCE = 0.85
GESTURE_STABLE_TARGET_MS = 90
GESTURE_STABLE_MIN_FRAMES = 2
GESTURE_STABLE_MAX_FRAMES = 10
EXPAND_OPEN_ARM_RATIO = 1.2
EXPAND_OPEN_DISTANCE_RATIO = 1.35
EXPAND_OPEN_MIN_STABLE_FRAMES = 4
EXPAND_OPEN_MIN_CONFIDENCE = 0.8

# --- Interaction Safety ---
ACTION_COOLDOWN_MS = 600
NAV_COOLDOWN_MS = 700
DELETE_HOLD_MS = 1200
SAFE_DELETE_MODE = "recycle_bin"
MODE_TOGGLE_COOLDOWN_MS = 900

# --- Desktop Control ---
DESKTOP_ACTION_COOLDOWN_MS = 350
DESKTOP_SCROLL_COOLDOWN_MS = 80
DESKTOP_SCROLL_DELTA = 120
DESKTOP_MAX_VOLUME_STEPS = 8
DESKTOP_CURSOR_SMOOTHING = 0.22
DESKTOP_CLICK_COOLDOWN_MS = 250
DESKTOP_NAV_COOLDOWN_MS = 700

# --- Depth Control ---
DEPTH_SMOOTHING_FRAMES = 5
DEPTH_PUSH_THRESHOLD = 0.14
DEPTH_PULL_THRESHOLD = -0.14
DEPTH_VELOCITY_SMOOTHING = 0.4
DEPTH_UI_SCALE_MIN = 0.86
DEPTH_UI_SCALE_MAX = 1.24

# --- Spatial Layout ---
SPATIAL_BASE_Z = 1.0
SPATIAL_PARENT_Z = 1.8
SPATIAL_FOCUS_Z = 0.65
SPATIAL_SMOOTHING_FACTOR = 0.18
GRAB_RADIUS = 40
GRAB_FOLLOW_SMOOTHING = 0.18
GRAB_BASE_Z = SPATIAL_FOCUS_Z
GRAB_DEPTH_SCALE = 0.75

# --- Radial Menu ---
RADIAL_MENU_TIMEOUT_MS = 2200
RADIAL_MENU_RADIUS = 118
RADIAL_MENU_ITEMS = [
    "open_app",
    "close_window",
    "next_window",
    "prev_window",
    "volume_up",
    "volume_down",
    "play_pause",
    "scroll_down",
]

# --- Smoothing (One Euro Filter) ---
ONE_EURO_MIN_CUTOFF = 0.05 # Lower for more smoothing at slow speeds
ONE_EURO_BETA = 4.0
ONE_EURO_DERIVATIVE_CUTOFF = 1.0

# --- UI Settings ---
WINDOW_TITLE = "Hologram OS"
FULLSCREEN = False  # Set to True for production
UI_WIDTH = 1280
UI_HEIGHT = 720
TARGET_FPS = 60
MIN_FPS = 30
ADAPTIVE_QUALITY = True

# --- Theme (Cyan Glow) ---
COLOR_BG = (0, 0, 0)
COLOR_PRIMARY = (0, 255, 255)       # Cyan
COLOR_SECONDARY = (0, 100, 255)     # Blue
COLOR_ACCENT = (255, 0, 128)        # Magenta/Pink for contrast
COLOR_TEXT = (255, 255, 255)
COLOR_WARNING = (255, 50, 50)
COLOR_SUCCESS = (50, 255, 50)

OPACITY_PANEL = 100 # 0-255
VISUAL_PROFILE = "cinematic"
GRID_ALPHA = 54
SCANLINE_ALPHA = 48
GLOW_ALPHA = 82
CURSOR_TRAIL_LENGTH = 24
OVERLAY_ENABLED = True
OVERLAY_DURATION = 1.5
OVERLAY_FADE_TIME = 0.3

# --- Filesystem ---
IGNORED_FOLDERS = ["System Volume Information", "$RECYCLE.BIN", "Windows", "Program Files", "Program Files (x86)"]
SYSTEM_DRIVES_ONLY = False # If True, might limit scope, usually False to see all basic drives
